### ISSUE TITLE
[comment] Da uma olhada no Fiber

### ISSUE THREAD

**Issue by marcopollivier** [joaoscorissa/gin-api-rest#2]
Achei que aqui seria o jeito mais eficiente de comunicar e não perder o contexto... 

dá uma olhada no [Fiber](https://github.com/gofiber/fiber). Ele também é bem fácil de usar, mas é mais performático do que a própria net/http 

dá uma olhada aqui nesse benchmark https://github.com/smallnest/go-web-framework-benchmark

**Comment by joaoscorissa** [comment]
Opa vou olhar!
